print("Knowledge is power!")
print("\n")
print("knowledge")
print("is")
print("power!")
print("\n")
print("|=========|")
print("|knowledge|")
print("|is       |")
print("|power!   |")
print("|=========|")